Repository pytorch/audio, pull requests merged in 2021-04, with the labels that each got.

#1415 Autograd tests for Transforms MFCC
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1411 [ROCM] add rocm support
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
  cmake/LoadHIP.cmake
  test/torchaudio_unittest/backend/soundfile/save_test.py
  test/torchaudio_unittest/common_utils/__init__.py
  test/torchaudio_unittest/common_utils/case_utils.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
Labels: cla signed

#1410 Make `F.phase_vocoder` and `T.TimeStretch` handle complex dtype
  test/torchaudio_unittest/functional/functional_cpu_test.py
  test/torchaudio_unittest/functional/functional_cuda_test.py
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/functional/librosa_compatibility_test.py
  test/torchaudio_unittest/functional/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/batch_consistency_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed, complex dtype migration

#1417 Add missing file to facilitate fixup patch
  .circleci/unittest/windows/scripts/environment.yml
Labels: cla signed

#1418 Sync environment.yml such that patch applies
  .circleci/unittest/windows/scripts/environment.yml
Labels: cla signed

#1366 Add `return_complex` to F.spectrogram and T.Spectrogram
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/librosa_compatibility_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed, complex dtype migration

#1416 Add Autograd test for T.Resample
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1424 Add autograd test for T.Fade
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1426 Remove an invalid resample comparison unit test
  test/torchaudio_unittest/functional/librosa_compatibility_test.py
Labels: cla signed

#1422 Add autograd test for T.ComputeDeltas
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1423 Refactor implementation of F.compute_deltas
  torchaudio/functional/functional.py
Labels: cla signed

#1425 Add autograd test for T.SpectralCentroid
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1433 Remove T.GriffinLim normalized constant
  torchaudio/transforms.py
Labels: cla signed

#1421 Add autograd test for T.GriffinLim
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed, complex dtype migration

#1428 Fixed jinja2 environment autoescape to enable select extensions
  .circleci/regenerate.py
Labels: cla signed

#1429 Fixed URLContext response leak
  torchaudio/datasets/utils.py
Labels: cla signed

#1413 Added CodeQL and Bandit security checks as GitHub Actions
  .github/workflows/bandit.yml
  .github/workflows/codeql.yml
Labels: cla signed

#1432 Revert "Refactor implementation of F.compute_deltas (#1423)"
  torchaudio/functional/functional.py
Labels: cla signed

#1435 refactors functional test
  test/torchaudio_unittest/functional/functional_cpu_test.py
  test/torchaudio_unittest/functional/functional_cuda_test.py
  test/torchaudio_unittest/functional/functional_impl.py
Labels: cla signed

#1434 Do not print CPU info before running tests
  .circleci/unittest/linux/scripts/run_test.sh
Labels: cla signed

#1436 Run functional librosa compatibility test on CUDA as well
  test/torchaudio_unittest/common_utils/__init__.py
  test/torchaudio_unittest/common_utils/data_utils.py
  test/torchaudio_unittest/common_utils/parameterized_utils.py
  test/torchaudio_unittest/functional/librosa_compatibility_cpu_test.py
  test/torchaudio_unittest/functional/librosa_compatibility_cuda_test.py
  test/torchaudio_unittest/functional/librosa_compatibility_test.py
  test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py
Labels: cla signed

#1438 Refactor `F.lfilter` and `F.*_biquad` autograd tests
  test/torchaudio_unittest/functional/autograd_impl.py
Labels: cla signed

#1437 Update InverseMelScale comparison test
  test/torchaudio_unittest/transforms/librosa_compatibility_test.py
  test/torchaudio_unittest/transforms/transforms_cpu_test.py
  test/torchaudio_unittest/transforms/transforms_cuda_test.py
  test/torchaudio_unittest/transforms/transforms_test_impl.py
Labels: cla signed, hackathon

#1439 Run transform librosa compatibility test on CUDA as well
  test/torchaudio_unittest/transforms/librosa_compatibility_cpu_test.py
  test/torchaudio_unittest/transforms/librosa_compatibility_cuda_test.py
  test/torchaudio_unittest/transforms/librosa_compatibility_test.py
  test/torchaudio_unittest/transforms/librosa_compatibility_test_impl.py
Labels: cla signed, hackathon

#1440 Added Windows build instructions
  README.md
Labels: cla signed

#1443 Shortening lfilter autograd tests input size
  test/torchaudio_unittest/functional/autograd_impl.py
Labels: cla signed

#1368 Adopt native complex dtype in griffnlim
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  torchaudio/functional/functional.py
Labels: cla signed, complex dtype migration

#1451 Remove VAD from batch consistency tests
  test/torchaudio_unittest/functional/batch_consistency_test.py
Labels: cla signed

#1445 Add deprecation warnings to functions for complex
  torchaudio/functional/functional.py
Labels: cla signed

#1447 Add autograd test for T.AmplitudeToDB
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1446 Save/load TorchScript object in test
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
Labels: cla signed

#1420 Add autograd test to T.TimeStretch (and F.phase_vocoder)
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed, complex dtype migration

#1455 Fixed floor_divide deprecation warnings seen in pytest output
  test/torchaudio_unittest/functional/functional_cpu_test.py
  torchaudio/functional/filtering.py
Labels: cla signed

#1444 Use torchaudio melscale 'slaney' instead of librosa in WaveRNN pipeline preprocessing
  examples/pipeline_wavernn/main.py
  examples/pipeline_wavernn/processing.py
Labels: cla signed

#1060 fix: dataset-root and dataset-folder-in-archive flag is empty
  examples/pipeline_wav2letter/README.md
Labels: cla signed

#1457 Fbsync: test sanitization and lint fix
  test/torchaudio_unittest/common_utils/parameterized_utils.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchscript_bc_test/assets/.gitignore
Labels: cla signed

#1458 Add missing transforms to __all__
  torchaudio/transforms.py
Labels: cla signed

#1460 Add autograd test for T.Vol
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1462 Explicitly disable wavpack when building SoX
  third_party/sox/CMakeLists.txt
Labels: cla signed

#1463 Refactor functional test
  test/torchaudio_unittest/functional/functional_cpu_test.py
  test/torchaudio_unittest/functional/functional_cuda_test.py
  test/torchaudio_unittest/functional/functional_impl.py
Labels: cla signed

#1465 Removed misc_ops module #1464
  torchaudio/_internal/misc_ops.py
Labels: cla signed

#778 Remove codecov and store coverage on CCI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/linux/scripts/post_process.sh
  .circleci/unittest/linux/scripts/run_test.sh
  .circleci/unittest/windows/scripts/install.sh
  .circleci/unittest/windows/scripts/post_process.sh
  .circleci/unittest/windows/scripts/run_test.sh
Labels: cla signed

#1466 Add Google Analytics support
  docs/source/conf.py
Labels: cla signed

#1459 Clarify `sox_effects.apply_effects_tensor` as CPU-only in Doc
  torchaudio/sox_effects/sox_effects.py
Labels: cla signed

#1471 Fix typo
  torchaudio/functional/functional.py
Labels: cla signed

#1467 Add autograd test for T.MelScale
  test/torchaudio_unittest/transforms/autograd_test_impl.py
Labels: cla signed

#1470 Add WER to readme in wav2letter pipeline
  examples/pipeline_wav2letter/README.md
  examples/pipeline_wav2letter/main.py
Labels: cla signed

#1474 Move windows GPU images to previous tag
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1475 Functionalgputest
  test/torchaudio_unittest/functional/functional_cpu_test.py
  test/torchaudio_unittest/functional/functional_impl.py
Labels: cla signed

#1479 Replace existing prototype RNNT
  .gitmodules
  docs/source/index.rst
  docs/source/rnnt_loss.rst
  docs/source/transducer.rst
  examples/libtorchaudio/CMakeLists.txt
  test/torchaudio_unittest/rnnt/__init__.py
  test/torchaudio_unittest/rnnt/numpy_transducer.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cpu_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  test/torchaudio_unittest/rnnt/utils.py
  test/torchaudio_unittest/transducer_test.py
  third_party/CMakeLists.txt
  third_party/transducer/CMakeLists.txt
  torchaudio/csrc/CMakeLists.txt
  torchaudio/csrc/rnnt/compute.cpp
  torchaudio/csrc/rnnt/compute_alphas.cpp
  torchaudio/csrc/rnnt/compute_betas.cpp
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/cpu/compute_alphas.cpp
  torchaudio/csrc/rnnt/cpu/compute_betas.cpp
  torchaudio/csrc/rnnt/cpu/cpu_kernels.h
  torchaudio/csrc/rnnt/cpu/cpu_transducer.h
  torchaudio/csrc/rnnt/cpu/kernel_utils.h
  torchaudio/csrc/rnnt/cpu/math.h
  torchaudio/csrc/rnnt/macros.cpp
  torchaudio/csrc/rnnt/macros.h
  torchaudio/csrc/rnnt/options.h
  torchaudio/csrc/rnnt/transducer.h
  torchaudio/csrc/rnnt/types.cpp
  torchaudio/csrc/rnnt/types.h
  torchaudio/csrc/rnnt/workspace.h
  torchaudio/csrc/transducer.cpp
  torchaudio/prototype/rnnt_loss.py
  torchaudio/prototype/transducer.py
Labels: cla signed, fb-exported
