Repository pytorch/audio, pull requests merged in 2021-11, with the labels that each got.

#1896 Updated compatibility matrix to include LTS version
  README.md
Labels: cla signed, ciflow/default

#1949 Add melkwargs setting for MFCC in HuBERT pipeline
  examples/hubert/utils/feature_utils.py
Labels: cla signed, ciflow/default, module: pipelines

#1953 Add wav2vec2 ASR German pretrained model from voxpopuli
  docs/source/pipelines.rst
  test/integration_tests/conftest.py
  test/integration_tests/wav2vec2_pipeline_test.py
  torchaudio/pipelines/__init__.py
  torchaudio/pipelines/_wav2vec2/impl.py
  torchaudio/pipelines/_wav2vec2/utils.py
Labels: cla signed, ciflow/default, new feature, module: pipelines

#1955 Update requirements.txt for doc build
  docs/requirements.txt
Labels: module: docs, cla signed, ciflow/default, improvement

#1954 Add wav2vec2 ASR Italian pretrained model from voxpopuli
  docs/source/pipelines.rst
  test/integration_tests/conftest.py
  test/integration_tests/wav2vec2_pipeline_test.py
  torchaudio/pipelines/__init__.py
  torchaudio/pipelines/_wav2vec2/impl.py
  torchaudio/pipelines/_wav2vec2/utils.py
Labels: cla signed, ciflow/default, new feature, module: pipelines

#1960 Fix bandit failure
  scripts/retrieve_prs.py
Labels: cla signed, ciflow/default, improvement, other

#1951 Refactor collecting-PR script for release note
  tools/retrieve_prs.py
Labels: cla signed, ciflow/default, improvement, other

#1947 Add citation information
  CITATION
  README.md
Labels: module: docs, cla signed, ciflow/default, improvement

#1939 Run integration tests on CI
  .github/workflows/integration-test.yml
  test/integration_tests/conftest.py
Labels: module: tests, cla signed, ciflow/default, improvement

#1962 Add citation information in the documentation
  docs/source/index.rst
Labels: cla signed, ciflow/default

#1963 Add citation to stable (0.10.0) doc
  0.10.0/index.html
Labels: cla signed, ciflow/default

#1964 Update PR label notifier
  .github/process_commit.py
  .github/workflows/pr-labels.yml
Labels: cla signed, ciflow/default

#1965 Revert "Update PR label notifier"
  .github/process_commit.py
  .github/workflows/pr-labels.yml
Labels: cla signed, ciflow/default

#1968 Support multi-node training for source separation pipeline
  examples/source_separation/README.md
  examples/source_separation/lightning_train.py
Labels: cla signed, ciflow/default, improvement, module: pipelines, bug fix

#1966 Fetch third party sources automatically
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  .github/workflows/codeql.yml
  .github/workflows/integration-test.yml
  setup.py
Labels: cla signed, ciflow/default

#1956 Add wav2vec2 ASR English pretrained model from voxpopuli
  docs/source/pipelines.rst
  test/integration_tests/conftest.py
  test/integration_tests/wav2vec2_pipeline_test.py
  torchaudio/pipelines/__init__.py
  torchaudio/pipelines/_wav2vec2/impl.py
  torchaudio/pipelines/_wav2vec2/utils.py
Labels: cla signed, ciflow/default, new feature, module: pipelines

#1958 [BC-Breaking] Drop pseudo complex support from spectrogram
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed, BC-breaking, ciflow/default, deprecation, module: ops

#1957 [BC-Breaking] Drop pseudo complex support from phase_vocoder / TimeStretch
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/batch_consistency_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed, BC-breaking, ciflow/default, module: ops

#1975 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: module: docs, cla signed, ciflow/default, improvement

#1974 Consolidate network utils
  test/integration_tests/conftest.py
  torchaudio/_internal/__init__.py
  torchaudio/pipelines/_tts/impl.py
  torchaudio/pipelines/_tts/utils.py
  torchaudio/pipelines/_wav2vec2/impl.py
Labels: cla signed, ciflow/default, other

#1971 [fbsync] Resolve lint warning
  tools/convert_voxpopuli_models.py
Labels: cla signed, ciflow/default, other, style

#1967 Add Sphinx-gallery to doc
  .flake8
  .gitignore
  docs/requirements.txt
  docs/source/backend.rst
  docs/source/compliance.kaldi.rst
  docs/source/conf.py
  docs/source/datasets.rst
  docs/source/functional.rst
  docs/source/index.rst
  docs/source/kaldi_io.rst
  docs/source/models.rst
  docs/source/pipelines.rst
  docs/source/prototype.rst
  docs/source/sox_effects.rst
  docs/source/transforms.rst
  docs/source/utils.rst
  examples/gallery/.gitignore
  examples/gallery/wav2vec2/README.rst
  examples/gallery/wav2vec2/forced_alignment_tutorial.py
  examples/gallery/wav2vec2/speech_recognition_pipeline_tutorial.py
Labels: module: docs, cla signed, ciflow/default, new feature

#1978 Update Jekyll config to serve Sphinx-Gallery images and notebooks
  _config.yml
Labels: module: docs, cla signed, ciflow/default, bug fix

#1977 Tweak doc build
  .circleci/build_docs/build_docs.sh
  CONTRIBUTING.md
  docs/requirements-tutorials.txt
  docs/requirements.txt
  docs/source/conf.py
Labels: cla signed, ciflow/default, improvement, other

#1969 Add Colab/Download/Github link similar to tutorials
  docs/source/_templates/layout.html
Labels: cla signed, ciflow/default

#1981 Fix colab URL
  docs/source/_templates/layout.html
Labels: module: docs, cla signed, ciflow/default, bug fix

#1980 Fix pytorch_sphinx_theme version
  docs/requirements.txt
Labels: module: docs, cla signed, ciflow/default, other

#1982 Docs fixes
  test/torchaudio_unittest/functional/functional_impl.py
  torchaudio/pipelines/_tts/interface.py
Labels: module: docs, cla signed, ciflow/default, improvement

#1985 Embed audio samples in generated tutorials
  examples/gallery/tts/tacotron2_pipeline_tutorial.py
  examples/gallery/wav2vec2/forced_alignment_tutorial.py
  examples/gallery/wav2vec2/speech_recognition_pipeline_tutorial.py
Labels: cla signed, ciflow/default

#1987 Refactor tutorial organization
  .flake8
  .gitignore
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/index.rst
  examples/gallery/.gitignore
  examples/gallery/tts/README.rst
  examples/gallery/wav2vec2/README.rst
  examples/tutorials/README.rst
  examples/tutorials/forced_alignment_tutorial.py
  examples/tutorials/speech_recognition_pipeline_tutorial.py
  examples/tutorials/tacotron2_pipeline_tutorial.py
Labels: cla signed, ciflow/default

#1970 Port Audio I/O tutorials
  docs/source/index.rst
  examples/tutorials/audio_data_augmentation_tutorial.py
  examples/tutorials/audio_datasets_tutorial.py
  examples/tutorials/audio_feature_augmentation_tutorial.py
  examples/tutorials/audio_feature_extractions_tutorial.py
  examples/tutorials/audio_io_tutorial.py
  examples/tutorials/audio_resampling_tutorial.py
Labels: module: docs, cla signed, ciflow/default, new feature

#1983 Port MVDR tutorial
  docs/source/index.rst
  examples/tutorials/mvdr_tutorial.py
Labels: cla signed, ciflow/default

#1989 Fix sections of MVDR
  examples/tutorials/mvdr_tutorial.py
Labels: module: docs, cla signed, ciflow/default, bug fix

#1988 Tweak index page
  docs/source/index.rst
Labels: cla signed, ciflow/default

#1997 Fix Wav2Vec2ASRBundle document page
  _config.yml
Labels: module: docs, cla signed, ciflow/default, bug fix

#1999 [Fbsync] Enable CLANGFORMAT
  examples/libtorchaudio/augmentation/main.cpp
  examples/libtorchaudio/speech_recognition/transcribe.cpp
  examples/libtorchaudio/speech_recognition/transcribe_list.cpp
Labels: cla signed, ciflow/default

#2002 Fix doctring
  torchaudio/pipelines/_wav2vec2/impl.py
Labels: cla signed, ciflow/default

#1998 Removing deprecated create_fb_matrix
  docs/source/functional.rst
  examples/tutorials/audio_feature_extractions_tutorial.py
  torchaudio/functional/__init__.py
  torchaudio/functional/functional.py
Labels: cla signed, ciflow/default

#1990 Add tutorial to CONTRIBUTING
  CONTRIBUTING.md
Labels: cla signed, ciflow/default

#2006 Fix style checks in examples/tutorials
  examples/tutorials/audio_data_augmentation_tutorial.py
  examples/tutorials/audio_datasets_tutorial.py
  examples/tutorials/audio_feature_augmentation_tutorial.py
  examples/tutorials/audio_feature_extractions_tutorial.py
  examples/tutorials/audio_io_tutorial.py
  examples/tutorials/audio_resampling_tutorial.py
  examples/tutorials/forced_alignment_tutorial.py
  examples/tutorials/mvdr_tutorial.py
  examples/tutorials/speech_recognition_pipeline_tutorial.py
  examples/tutorials/tacotron2_pipeline_tutorial.py
Labels: cla signed, ciflow/default, improvement, example

#2008 Add script for classifying release note PRs
  tools/release_notes/classify_prs.py
  tools/release_notes/retrieve_prs.py
Labels: cla signed, ciflow/default, other
