Repository pytorch/audio, pull requests merged in 2021-09, with the labels that each got.

#1743 Add edit_distance to documentation with a new category Metric
  docs/source/functional.rst
Labels: cla signed

#1745 Update the version of fairseq used for testing model
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
Labels: cla signed

#1747 Build torchaudio for 11.3 as well
  .circleci/config.yml
  .circleci/regenerate.py
  packaging/pkg_helpers.bash
Labels: cla signed

#1751 Upload wheels to respective folders
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
Labels: cla signed

#1748 Add link to TTS colab example to README
  examples/pipeline_tacotron2/README.md
Labels: cla signed

#1746 Standardize optional types in docstrings
  examples/pipeline_tacotron2/datasets.py
  examples/pipeline_tacotron2/text/text_preprocessing.py
  examples/pipeline_wavernn/wavernn_inference_wrapper.py
  examples/source_separation/utils/dataset/wsj0mix.py
  examples/source_separation/utils/metrics.py
  torchaudio/backend/soundfile_backend.py
  torchaudio/backend/sox_io_backend.py
  torchaudio/backend/utils.py
  torchaudio/datasets/gtzan.py
  torchaudio/datasets/speechcommands.py
  torchaudio/datasets/tedlium.py
  torchaudio/datasets/utils.py
  torchaudio/datasets/vctk.py
  torchaudio/functional/filtering.py
  torchaudio/functional/functional.py
  torchaudio/models/conv_tasnet.py
  torchaudio/models/wav2vec2/components.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
  torchaudio/sox_effects/sox_effects.py
  torchaudio/transforms.py
Labels: cla signed

#1744 Put output tensor on proper device in `get_whitenoise()`
  test/torchaudio_unittest/common_utils/data_utils.py
  test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py
Labels: cla signed

#1739 Extract PyBind11 feature implementations
  torchaudio/csrc/CMakeLists.txt
  torchaudio/csrc/pybind/pybind.cpp
  torchaudio/csrc/pybind/sox/effects.cpp
  torchaudio/csrc/pybind/sox/effects.h
  torchaudio/csrc/pybind/sox/effects_chain.cpp
  torchaudio/csrc/pybind/sox/effects_chain.h
  torchaudio/csrc/pybind/sox/io.cpp
  torchaudio/csrc/pybind/sox/io.h
  torchaudio/csrc/pybind/sox/utils.cpp
  torchaudio/csrc/pybind/sox/utils.h
  torchaudio/csrc/sox/effects.cpp
  torchaudio/csrc/sox/effects.h
  torchaudio/csrc/sox/effects_chain.cpp
  torchaudio/csrc/sox/effects_chain.h
  torchaudio/csrc/sox/io.cpp
  torchaudio/csrc/sox/io.h
  torchaudio/csrc/sox/utils.cpp
  torchaudio/csrc/sox/utils.h
Labels: fb-exported, cla signed

#1755 Update the way to access libsox global config
  torchaudio/csrc/pybind/sox/effects.cpp
  torchaudio/csrc/pybind/sox/io.cpp
Labels: cla signed

#1729 [ROCM] fix build error
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
Labels: cla signed

#1764 Pin MKL to 2021.2.0 (#1655)
  .circleci/unittest/linux/scripts/install.sh
  packaging/pkg_helpers.bash
  packaging/torchaudio/meta.yaml
Labels: cla signed

#1760 [v0.9.1] .circleci: Bump versions for pytorch 1.9.1
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1765 Add normalization to steering vector solutions in MVDR Module
  examples/beamforming/mvdr.py
Labels: cla signed

#1766 [fbsync] Style fixes
  torchaudio/csrc/CMakeLists.txt
  torchaudio/csrc/pybind/sox/effects.cpp
  torchaudio/csrc/pybind/sox/effects.h
  torchaudio/csrc/pybind/sox/effects_chain.cpp
  torchaudio/csrc/pybind/sox/effects_chain.h
  torchaudio/csrc/pybind/sox/io.cpp
  torchaudio/csrc/pybind/sox/io.h
  torchaudio/csrc/pybind/sox/utils.cpp
  torchaudio/csrc/pybind/sox/utils.h
  torchaudio/csrc/sox/effects.cpp
  torchaudio/csrc/sox/effects.h
  torchaudio/csrc/sox/effects_chain.cpp
  torchaudio/csrc/sox/effects_chain.h
  torchaudio/csrc/sox/io.h
Labels: cla signed

#1767 Migrate CircleCI docker image
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1752 Split extension into non-Python and Python wrapper libraries
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
  examples/libtorchaudio/CMakeLists.txt
  torchaudio/__init__.py
  torchaudio/_extension.py
  torchaudio/csrc/CMakeLists.txt
Labels: cla signed

#1772 Refactor batch consistency test in transforms
  test/torchaudio_unittest/transforms/batch_consistency_test.py
Labels: cla signed

#1774 Fix typo in source separation README
  examples/source_separation/README.md
Labels: cla signed

#1775 Fix indentation and grouping
  docs/source/models.rst
Labels: cla signed

#1771 Move MVDR and PSD modules to transforms
  docs/source/refs.bib
  docs/source/transforms.rst
  examples/beamforming/mvdr.py
  test/torchaudio_unittest/common_utils/psd_utils.py
  test/torchaudio_unittest/example/beamforming/__init__.py
  test/torchaudio_unittest/example/beamforming/autograd_cpu_test.py
  test/torchaudio_unittest/example/beamforming/autograd_cuda_test.py
  test/torchaudio_unittest/example/beamforming/autograd_test_impl.py
  test/torchaudio_unittest/example/beamforming/batch_consistency_test.py
  test/torchaudio_unittest/example/beamforming/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/example/beamforming/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/example/beamforming/torchscript_consistency_impl.py
  test/torchaudio_unittest/example/beamforming/transforms_cpu_test.py
  test/torchaudio_unittest/example/beamforming/transforms_cuda_test.py
  test/torchaudio_unittest/example/beamforming/transforms_test_impl.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/batch_consistency_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/transforms_test_impl.py
  torchaudio/transforms.py
Labels: cla signed

#1773 Put libtorchaudio in lib directory
  build_tools/setup_helpers/extension.py
  torchaudio/_extension.py
  torchaudio/csrc/CMakeLists.txt
  torchaudio/lib/.gitignore
Labels: cla signed

#1776 [BC-Breaking] Update `extract_features` of Wav2Vec2Model
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
  torchaudio/models/wav2vec2/components.py
  torchaudio/models/wav2vec2/model.py
Labels: cla signed, BC-Breaking

#1780 Tweak test name by appending factory function name
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
Labels: cla signed

#1784 [Fbsync] Update URL for fairseq repo
  examples/libtorchaudio/speech_recognition/README.md
  test/torchaudio_unittest/assets/wav2vec2/fairseq/generate_fairseq_model_config.py
Labels: cla signed

#1781 Fix HF model integration
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
  torchaudio/models/wav2vec2/utils/import_huggingface.py
Labels: cla signed

#1782 [BC-Breaking] Move fine-tune specific module out of wav2vec2 encoder
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
  torchaudio/models/wav2vec2/components.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
  torchaudio/models/wav2vec2/utils/import_huggingface.py
Labels: cla signed

#1786 update windows gpu image from previous to stable
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1788 set libtorchaudio suffix as pyd on Windows
  torchaudio/_extension.py
  torchaudio/csrc/CMakeLists.txt
Labels: cla signed

#1768 Add MVDR beamforming tutorial to example directory
  examples/beamforming/MVDR_tutorial.ipynb
Labels: cla signed

#1787 Enable audio build on Windows with CUDA
  CMakeLists.txt
Labels: cla signed

#1783 [BC-Breaking] Split pretraining and finetuning factory functions
  docs/source/models.rst
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
  torchaudio/models/__init__.py
  torchaudio/models/wav2vec2/__init__.py
  torchaudio/models/wav2vec2/components.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
  torchaudio/models/wav2vec2/utils/import_huggingface.py
Labels: cla signed, BC-Breaking

#1790 [doc] Fix return type of wav2vec2 model
  torchaudio/models/wav2vec2/model.py
Labels: cla signed

#1789 [DOC] Add equations to MVDR Docstring
  torchaudio/transforms.py
Labels: cla signed

#1777 Enable audio windows cuda tests
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/windows/scripts/install.sh
  .circleci/unittest/windows/scripts/run_test.sh
  .circleci/unittest/windows/scripts/set_cuda_envs.sh
  packaging/windows/internal/cuda_install.bat
  packaging/windows/internal/driver_update.bat
Labels: cla signed

#1793 Update the main version to 0.11.0
  README.md
  packaging/build_conda.sh
  packaging/build_wheel.sh
  setup.py
Labels: cla signed

#1769 Add HuBERT model architectures
  docs/source/models.rst
  docs/source/refs.bib
  test/torchaudio_unittest/assets/wav2vec2/fairseq/generate_hubert_model_config.py
  test/torchaudio_unittest/assets/wav2vec2/fairseq/generate_wav2vec2_model_config.py
  test/torchaudio_unittest/assets/wav2vec2/fairseq/hubert_base_ls960.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/hubert_large_ll60k.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/hubert_large_ll60k_finetune_ls960.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/hubert_xtralarge_ll60k.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/hubert_xtralarge_ll60k_finetune_ls960.json
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
  torchaudio/models/__init__.py
  torchaudio/models/wav2vec2/__init__.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
Labels: cla signed

#1800 Skip hubert_asr_xlargeTS test on Windows
  test/torchaudio_unittest/models/wav2vec2/model_test.py
Labels: cla signed

#1803 [fbsync] Remove trailing whitespace
  CMakeLists.txt
Labels: cla signed

#1795 update windows cuda installer 11.1.0 to 11.1.1
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#1804 Rename factory functions `wav2vec2_asr_YYY` to `wav2vec2_ft_YYY`
  docs/source/models.rst
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
  torchaudio/models/__init__.py
  torchaudio/models/wav2vec2/__init__.py
  torchaudio/models/wav2vec2/model.py
Labels: cla signed

#1802 Replace issue templates with new issue forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/questions-help-support.md
Labels: cla signed

#1810 Deprecate VCTK
  torchaudio/datasets/vctk.py
Labels: cla signed

#1813 Add unmaintained warnings
  examples/interactive_asr/README.md
Labels: cla signed

#1807 Skip hubert_xlarge TS test on Windows
  test/torchaudio_unittest/models/wav2vec2/model_test.py
Labels: cla signed

#1809 Deprecate data utils
  torchaudio/datasets/utils.py
Labels: cla signed
