Repository pytorch/audio, pull requests merged in 2021-06, with the labels that each got.

#1531 Add fairseq importer
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  docs/source/models.rst
  test/torchaudio_unittest/assets/wav2vec2/fairseq/generate_fairseq_model_config.py
  test/torchaudio_unittest/assets/wav2vec2/fairseq/libri960_big.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_large_960h.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_large_lv60k_960h.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_large_lv60k_self_960h.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_small.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_small_960h.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/wav2vec_vox_new.json
  test/torchaudio_unittest/assets/wav2vec2/fairseq/xlsr_53_56k.json
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  torchaudio/models/wav2vec2/utils/__init__.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
Labels: cla signed

#1537 Ensure resampling identity is unchanged
  test/torchaudio_unittest/compliance_kaldi_test.py
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/transforms/transforms_test_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed

#1540 Disable GPU binary builds in release branch
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#1541 Remove prototype from 0.9 release
  .circleci/torchscript_bc_test/common.sh
  .circleci/unittest/linux/scripts/install.sh
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
  docs/source/index.rst
  docs/source/rnnt_loss.rst
  examples/libtorchaudio/CMakeLists.txt
  packaging/build_wheel.sh
  packaging/torchaudio/build.sh
  test/torchaudio_unittest/rnnt/__init__.py
  test/torchaudio_unittest/rnnt/numpy_transducer.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cpu_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cuda_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_impl.py
  test/torchaudio_unittest/rnnt/utils.py
  torchaudio/csrc/CMakeLists.txt
  torchaudio/csrc/rnnt/autograd.cpp
  torchaudio/csrc/rnnt/compute.cpp
  torchaudio/csrc/rnnt/compute.h
  torchaudio/csrc/rnnt/compute_alphas.cpp
  torchaudio/csrc/rnnt/compute_betas.cpp
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/cpu/compute_alphas.cpp
  torchaudio/csrc/rnnt/cpu/compute_betas.cpp
  torchaudio/csrc/rnnt/cpu/cpu_kernels.h
  torchaudio/csrc/rnnt/cpu/cpu_transducer.h
  torchaudio/csrc/rnnt/cpu/kernel_utils.h
  torchaudio/csrc/rnnt/cpu/math.h
  torchaudio/csrc/rnnt/gpu/compute.cu
  torchaudio/csrc/rnnt/gpu/compute_alphas.cu
  torchaudio/csrc/rnnt/gpu/compute_betas.cu
  torchaudio/csrc/rnnt/gpu/gpu_kernel_utils.cuh
  torchaudio/csrc/rnnt/gpu/gpu_kernels.cuh
  torchaudio/csrc/rnnt/gpu/gpu_transducer.h
  torchaudio/csrc/rnnt/gpu/half.cuh
  torchaudio/csrc/rnnt/gpu/kernel_utils.h
  torchaudio/csrc/rnnt/gpu/kernels.h
  torchaudio/csrc/rnnt/gpu/math.cuh
  torchaudio/csrc/rnnt/macros.cpp
  torchaudio/csrc/rnnt/macros.h
  torchaudio/csrc/rnnt/options.h
  torchaudio/csrc/rnnt/types.cpp
  torchaudio/csrc/rnnt/types.h
  torchaudio/csrc/rnnt/workspace.h
  torchaudio/prototype/__init__.py
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1539 Set release version
  .circleci/config.yml
  .circleci/config.yml.in
  docs/source/conf.py
Labels: cla signed

#1543 Remove codecov badge from README
  README.md
Labels: cla signed

#1546 Update the master version to 0.10
  packaging/build_conda.sh
  packaging/build_wheel.sh
  setup.py
Labels: cla signed

#1544 Update README
  README.md
Labels: cla signed

#1548 Reformat resample docs
  docs/source/functional.rst
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed

#1550 Update docs
  docs/requirements.txt
  docs/source/_static/css/override.css
  docs/source/_static/css/pytorch_theme.css
  docs/source/conf.py
  docs/source/functional.rst
  docs/source/models.rst
  docs/source/refs.bib
  docs/source/rnnt_loss.rst
  docs/source/transforms.rst
  torchaudio/backend/soundfile_backend.py
  torchaudio/functional/filtering.py
  torchaudio/functional/functional.py
  torchaudio/models/conv_tasnet.py
  torchaudio/models/deepspeech.py
  torchaudio/models/wav2letter.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wav2vec2/utils/import_fairseq.py
  torchaudio/models/wav2vec2/utils/import_huggingface.py
  torchaudio/models/wavernn.py
  torchaudio/prototype/rnnt_loss.py
  torchaudio/transforms.py
Labels: cla signed

#1551 Ignore return_complex when returning real-valued tensor in spectrogram.
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed

#1520 Migrate kaldi resample tests to functional
  test/torchaudio_unittest/compliance_kaldi_test.py
  test/torchaudio_unittest/functional/batch_consistency_test.py
  test/torchaudio_unittest/functional/functional_impl.py
Labels: cla signed

#1532 RNN Transducer Loss Autograd Test
  test/torchaudio_unittest/rnnt/autograd_cpu_test.py
  test/torchaudio_unittest/rnnt/autograd_cuda_test.py
  test/torchaudio_unittest/rnnt/autograd_impl.py
  test/torchaudio_unittest/rnnt/numpy_transducer.py
Labels: cla signed

#1553 Set removal version of pseudo complex support
  torchaudio/functional/functional.py
Labels: cla signed, complex dtype migration

#1549 [BC-Breaking] Default to native complex type when returning raw spect…
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: BC-Breaking, cla signed, complex dtype migration

#1555 [BC-Breaking] Remove kaldi.resample_waveform
  docs/source/compliance.kaldi.rst
  test/torchaudio_unittest/assets/kaldi/resample-16000-1000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-10000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-11000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-12000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-13000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-14000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-15000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-16000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-17000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-18000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-19000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-2000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-20000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-21000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-22000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-23000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-24000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-25000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-26000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-27000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-28000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-29000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-3000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-30000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-31000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-32000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-4000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-5000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-6000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-7000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-8000.ark
  test/torchaudio_unittest/assets/kaldi/resample-16000-9000.ark
  test/torchaudio_unittest/compliance/__init__.py
  test/torchaudio_unittest/compliance/generate_fbank_data.py
  test/torchaudio_unittest/compliance/generate_test_stft_data.py
  test/torchaudio_unittest/compliance/utils.py
  test/torchaudio_unittest/compliance_kaldi_test.py
  torchaudio/compliance/kaldi.py
Labels: BC-Breaking, cla signed

#1554 Remove override CSS
  docs/source/_static/css/override.css
  docs/source/conf.py
Labels: cla signed

#1559 Update skipIfNoCuda decorator/Force GPU tests run in GPU CIs
  .circleci/config.yml
  .circleci/config.yml.in
  test/torchaudio_unittest/common_utils/case_utils.py
Labels: cla signed

#1567 Update docs
  torchaudio/transforms.py
Labels: cla signed

#1568 0.9.0 generate new docs
  0.9.0/.buildinfo
  0.9.0/_modules/index.html
  0.9.0/_modules/torchaudio/backend/common.html
  0.9.0/_modules/torchaudio/backend/soundfile_backend.html
  0.9.0/_modules/torchaudio/backend/sox_io_backend.html
  0.9.0/_modules/torchaudio/backend/utils.html
  0.9.0/_modules/torchaudio/compliance/kaldi.html
  0.9.0/_modules/torchaudio/datasets/cmuarctic.html
  0.9.0/_modules/torchaudio/datasets/commonvoice.html
  0.9.0/_modules/torchaudio/datasets/gtzan.html
  0.9.0/_modules/torchaudio/datasets/librispeech.html
  0.9.0/_modules/torchaudio/datasets/libritts.html
  0.9.0/_modules/torchaudio/datasets/ljspeech.html
  0.9.0/_modules/torchaudio/datasets/speechcommands.html
  0.9.0/_modules/torchaudio/datasets/tedlium.html
  0.9.0/_modules/torchaudio/datasets/vctk.html
  0.9.0/_modules/torchaudio/datasets/yesno.html
  0.9.0/_modules/torchaudio/functional/filtering.html
  0.9.0/_modules/torchaudio/functional/functional.html
  0.9.0/_modules/torchaudio/kaldi_io.html
  0.9.0/_modules/torchaudio/models/conv_tasnet.html
  0.9.0/_modules/torchaudio/models/deepspeech.html
  0.9.0/_modules/torchaudio/models/wav2letter.html
  0.9.0/_modules/torchaudio/models/wav2vec2/model.html
  0.9.0/_modules/torchaudio/models/wav2vec2/utils/import_fairseq.html
  0.9.0/_modules/torchaudio/models/wav2vec2/utils/import_huggingface.html
  0.9.0/_modules/torchaudio/models/wavernn.html
  0.9.0/_modules/torchaudio/sox_effects/sox_effects.html
  0.9.0/_modules/torchaudio/transforms.html
  0.9.0/_modules/torchaudio/utils/sox_utils.html
  0.9.0/_static/documentation_options.js
  0.9.0/_static/jquery-3.5.1.js
  0.9.0/_static/pygments.css
  0.9.0/_static/underscore-1.12.0.js
  0.9.0/backend.html
  0.9.0/compliance.kaldi.html
  0.9.0/datasets.html
  0.9.0/functional.html
  0.9.0/genindex.html
  0.9.0/index.html
  0.9.0/kaldi_io.html
  0.9.0/models.html
  0.9.0/py-modindex.html
  0.9.0/search.html
  0.9.0/searchindex.js
  0.9.0/sox_effects.html
  0.9.0/torchaudio.html
  0.9.0/transforms.html
  0.9.0/utils.html
Labels: cla signed

#1572 Update MelSpectrogram power annotation
  torchaudio/transforms.py
Labels: cla signed

#1575 [Cherry-picked 0.9] Add name of paper before reference.
  torchaudio/functional/functional.py
  torchaudio/models/conv_tasnet.py
  torchaudio/models/deepspeech.py
  torchaudio/models/wav2letter.py
  torchaudio/models/wav2vec2/model.py
  torchaudio/models/wavernn.py
  torchaudio/prototype/rnnt_loss.py
  torchaudio/transforms.py
Labels: cla signed

#1577 fix tag build so it triggers prerequisites
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#1580 link stable to 0.9.0 docs, update versions.html
  stable
  versions.html
Labels: cla signed

#1581 DOC: Remove git tag from 0.9.0 pages titles
  0.9.0/_modules/index.html
  0.9.0/_modules/torchaudio/backend/common.html
  0.9.0/_modules/torchaudio/backend/soundfile_backend.html
  0.9.0/_modules/torchaudio/backend/sox_io_backend.html
  0.9.0/_modules/torchaudio/backend/utils.html
  0.9.0/_modules/torchaudio/compliance/kaldi.html
  0.9.0/_modules/torchaudio/datasets/cmuarctic.html
  0.9.0/_modules/torchaudio/datasets/commonvoice.html
  0.9.0/_modules/torchaudio/datasets/gtzan.html
  0.9.0/_modules/torchaudio/datasets/librispeech.html
  0.9.0/_modules/torchaudio/datasets/libritts.html
  0.9.0/_modules/torchaudio/datasets/ljspeech.html
  0.9.0/_modules/torchaudio/datasets/speechcommands.html
  0.9.0/_modules/torchaudio/datasets/tedlium.html
  0.9.0/_modules/torchaudio/datasets/vctk.html
  0.9.0/_modules/torchaudio/datasets/yesno.html
  0.9.0/_modules/torchaudio/functional/filtering.html
  0.9.0/_modules/torchaudio/functional/functional.html
  0.9.0/_modules/torchaudio/kaldi_io.html
  0.9.0/_modules/torchaudio/models/conv_tasnet.html
  0.9.0/_modules/torchaudio/models/deepspeech.html
  0.9.0/_modules/torchaudio/models/wav2letter.html
  0.9.0/_modules/torchaudio/models/wav2vec2/model.html
  0.9.0/_modules/torchaudio/models/wav2vec2/utils/import_fairseq.html
  0.9.0/_modules/torchaudio/models/wav2vec2/utils/import_huggingface.html
  0.9.0/_modules/torchaudio/models/wavernn.html
  0.9.0/_modules/torchaudio/sox_effects/sox_effects.html
  0.9.0/_modules/torchaudio/transforms.html
  0.9.0/_modules/torchaudio/utils/sox_utils.html
  0.9.0/backend.html
  0.9.0/compliance.kaldi.html
  0.9.0/datasets.html
  0.9.0/functional.html
  0.9.0/genindex.html
  0.9.0/index.html
  0.9.0/kaldi_io.html
  0.9.0/models.html
  0.9.0/py-modindex.html
  0.9.0/search.html
  0.9.0/sox_effects.html
  0.9.0/torchaudio.html
  0.9.0/transforms.html
  0.9.0/utils.html
Labels: cla signed

#1582 Remove NumPy dependency from README
  README.md
Labels: cla signed

#1585 Fix HF wav2vec2 integration test
  test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
Labels: cla signed

#1588 Remove unused stuff
  .travis.yml
  test/torchscript_bc_test/README.md
  test/torchscript_bc_test/main.py
  test/torchscript_bc_test/ver_060.py
Labels: cla signed

#1599 Remove residuals for removed modules
  torchaudio/__init__.py
Labels: cla signed

#1598 Temporarily pin nightly version on Linux/macOS CPU unittest
  .circleci/unittest/linux/scripts/install.sh
Labels: cla signed

#1605 Update unit test CUDA to 10.2
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1606 [HOT FIX] Temporarily pin nightly version on Linux GPU unit test
  .circleci/unittest/linux/scripts/install.sh
Labels: cla signed

#1584 Update the installation and testing instructions.
  CONTRIBUTING.md
  test/torchaudio_unittest/README.md
Labels: cla signed

#1591 Add return type for RNNT loss
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1602 Rename RNNT loss C++ parameters
  torchaudio/csrc/rnnt/autograd.cpp
  torchaudio/csrc/rnnt/compute.cpp
  torchaudio/csrc/rnnt/compute.h
  torchaudio/csrc/rnnt/compute_alphas.cpp
  torchaudio/csrc/rnnt/compute_betas.cpp
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/cpu/compute_alphas.cpp
  torchaudio/csrc/rnnt/cpu/compute_betas.cpp
  torchaudio/csrc/rnnt/gpu/compute.cu
  torchaudio/csrc/rnnt/gpu/compute_alphas.cu
  torchaudio/csrc/rnnt/gpu/compute_betas.cu
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1590 Add reduction parameter for RNNT loss
  test/torchaudio_unittest/rnnt/utils.py
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1601 Porting edit distance from torchaudio.metrics to torchaudio.functional
  examples/pipeline_wav2letter/main.py
  examples/pipeline_wav2letter/metrics.py
  test/torchaudio_unittest/functional/functional_impl.py
  torchaudio/functional/__init__.py
  torchaudio/functional/functional.py
Labels: cla signed

#1613 Update config.[sub|guess] for lame and libmad
  third_party/sox/CMakeLists.txt
  third_party/sox/patch/config.guess
  third_party/sox/patch/config.sub
Labels: cla signed

#1609 Expose USE_CUDA in build
  build_tools/setup_helpers/extension.py
Labels: cla signed

#1603 Rename transducer to RNNT
  .circleci/torchscript_bc_test/common.sh
  .circleci/unittest/linux/scripts/install.sh
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
  examples/libtorchaudio/CMakeLists.txt
  packaging/build_wheel.sh
  packaging/torchaudio/build.sh
  test/torchaudio_unittest/rnnt/autograd_cpu_test.py
  test/torchaudio_unittest/rnnt/autograd_cuda_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cpu_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cuda_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/rnnt/utils.py
  torchaudio/csrc/CMakeLists.txt
Labels: cla signed

#1597 ci: Remove mentions of conda-forge for Python 3.9
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/torchscript_bc_test/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  packaging/pkg_helpers.bash
Labels: cla signed
