Repository pytorch/audio, pull requests merged in 2021-08, with the labels that each got.

#1653 Add melscale_fbanks and deprecate create_fb_matrix
  docs/source/functional.rst
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  torchaudio/functional/__init__.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed

#1627 Add CMUDict dataset
  docs/source/datasets.rst
  test/torchaudio_unittest/datasets/cmudict_test.py
  torchaudio/datasets/__init__.py
  torchaudio/datasets/cmudict.py
Labels: cla signed

#1663 Refactor coding style for wavernn example
  examples/pipeline_wavernn/datasets.py
  examples/pipeline_wavernn/inference.py
  examples/pipeline_wavernn/main.py
  examples/pipeline_wavernn/wavernn_inference_wrapper.py
Labels: cla signed

#1658 Added example for ComplexNorm
  torchaudio/transforms.py
Labels: cla signed

#1664 Fix models import
  torchaudio/__init__.py
Labels: cla signed

#1665 Fix encoding of CMUDict data reading
  torchaudio/datasets/cmudict.py
Labels: cla signed

#1649 Simplify extension initialization
  torchaudio/extension/extension.py
Labels: cla signed

#1610 Remove reuse_logits_for_grads option for RNNTL
  test/torchaudio_unittest/rnnt/autograd_impl.py
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  test/torchaudio_unittest/rnnt/utils.py
  torchaudio/csrc/rnnt/autograd.cpp
  torchaudio/csrc/rnnt/compute.cpp
  torchaudio/csrc/rnnt/compute.h
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/gpu/compute.cu
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1667 Add style checks on example files on CI
  .circleci/unittest/linux/scripts/run_style_checks.sh
  examples/interactive_asr/__init__.py
  examples/libtorchaudio/speech_recognition/parse_voxforge.py
  examples/source_separation/conv_tasnet/__init__.py
  examples/source_separation/conv_tasnet/train.py
  examples/source_separation/utils/__init__.py
  examples/source_separation/utils/dataset/__init__.py
  examples/source_separation/utils/dataset/utils.py
Labels: cla signed

#1615 Remove fused_log_softmax option from RNNT Loss
  test/torchaudio_unittest/rnnt/autograd_impl.py
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  test/torchaudio_unittest/rnnt/utils.py
  torchaudio/csrc/rnnt/autograd.cpp
  torchaudio/csrc/rnnt/compute.cpp
  torchaudio/csrc/rnnt/compute.h
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/gpu/compute.cu
  torchaudio/csrc/rnnt/gpu/gpu_kernels.cuh
  torchaudio/csrc/rnnt/gpu/gpu_transducer.h
  torchaudio/csrc/rnnt/gpu/kernels.h
  torchaudio/csrc/rnnt/options.h
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1620 Improve RNNT Loss docstrings
  torchaudio/prototype/rnnt_loss.py
Labels: cla signed

#1642 Add tacotron2 training script
  examples/pipeline_tacotron2/README.md
  examples/pipeline_tacotron2/datasets.py
  examples/pipeline_tacotron2/train.py
  examples/pipeline_tacotron2/utils.py
Labels: cla signed

#1670 Fix spacing
  examples/pipeline_tacotron2/datasets.py
  examples/pipeline_wavernn/README.md
Labels: cla signed

#1586 Example for Mu law encoding
  torchaudio/transforms.py
Labels: cla signed

#1566 Example code for Spectrogram in documentation
  torchaudio/transforms.py
Labels: cla signed

#1680 [Fbsync] Move test initialization logic to dedicated directory
  test/torchaudio_unittest/__init__.py
Labels: cla signed

#1683 Add documentation for CMUDict's property
  torchaudio/datasets/cmudict.py
Labels: cla signed

#1684 Example code for MuLawDecoding Transform
  torchaudio/transforms.py
Labels: cla signed

#1688 Update version setup.py for LTS
  .circleci/config.yml
  .circleci/config.yml.in
  setup.py
Labels: cla signed

#1648 Add Tacotron2 inference method
  test/torchaudio_unittest/models/tacotron2/model_test_impl.py
  torchaudio/prototype/tacotron2.py
Labels: cla signed

#1638 feat: lfilter with batch support
  test/torchaudio_unittest/functional/autograd_impl.py
  test/torchaudio_unittest/functional/batch_consistency_test.py
  test/torchaudio_unittest/functional/functional_impl.py
  torchaudio/functional/filtering.py
Labels: cla signed

#1668 Add phoneme text preprocessing for Tacotron2
  examples/pipeline_tacotron2/README.md
  examples/pipeline_tacotron2/text/text_preprocessing.py
  examples/pipeline_tacotron2/train.py
  examples/pipeline_tacotron2/utils.py
Labels: cla signed

#1652 Add InverseSpectrogram to transforms and functional
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/batch_consistency_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/transforms_test_impl.py
  torchaudio/functional/__init__.py
  torchaudio/functional/functional.py
  torchaudio/transforms.py
Labels: cla signed

#1693 Add tacotron2 pretrained models
  torchaudio/prototype/tacotron2.py
Labels: cla signed

#1697 packaging: Ensure we're propagating BUILD_VERSION
  packaging/torchaudio/meta.yaml
Labels: build, cla signed

#1698 Refactor lfilter docs
  torchaudio/functional/filtering.py
Labels: cla signed

#1695 Add prototype page to docs
  docs/source/index.rst
  docs/source/refs.bib
  docs/source/tacotron2.rst
  torchaudio/prototype/tacotron2.py
Labels: cla signed

#1701 [lts/release/1.8] packaging: Ensure we're propagating BUILD_VERSION (#1697)
  packaging/torchaudio/meta.yaml
Labels: build, cla signed

#1700 [Fbsync] Update pitch shift batch consistency test
  test/torchaudio_unittest/transforms/batch_consistency_test.py
Labels: cla signed

#1706 Add docs for InverseSpectrogram
  docs/source/functional.rst
  docs/source/transforms.rst
Labels: cla signed

#1654 Add an inference example for Tacotron2
  examples/pipeline_tacotron2/README.md
  examples/pipeline_tacotron2/inference.py
Labels: cla signed

#1707 RNNT Loss remove null grads
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  torchaudio/csrc/rnnt/cpu/compute.cpp
  torchaudio/csrc/rnnt/gpu/compute.cu
Labels: cla signed

#1714 Move Tacotron2 out of prototype
  docs/source/index.rst
  docs/source/models.rst
  docs/source/tacotron2.rst
  examples/pipeline_tacotron2/inference.py
  examples/pipeline_tacotron2/train.py
  test/torchaudio_unittest/models/tacotron2/model_test_impl.py
  torchaudio/models/__init__.py
  torchaudio/models/tacotron2.py
Labels: cla signed

#1716 Fix Tacotron2 inference example
  examples/pipeline_tacotron2/inference.py
Labels: cla signed

#1715 Guard Kaldi's version generation
  third_party/kaldi/CMakeLists.txt
Labels: cla signed

#1711 Move RNNTL out of prototype
  CMakeLists.txt
  README.md
  build_tools/setup_helpers/extension.py
  docs/source/functional.rst
  docs/source/index.rst
  docs/source/rnnt_loss.rst
  docs/source/transforms.rst
  examples/libtorchaudio/CMakeLists.txt
  examples/libtorchaudio/README.md
  packaging/build_wheel.sh
  packaging/torchaudio/build.sh
  test/torchaudio_unittest/common_utils/rnnt_utils.py
  test/torchaudio_unittest/functional/autograd_cpu_test.py
  test/torchaudio_unittest/functional/autograd_cuda_test.py
  test/torchaudio_unittest/functional/autograd_impl.py
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/functional/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  test/torchaudio_unittest/rnnt/__init__.py
  test/torchaudio_unittest/rnnt/autograd_cpu_test.py
  test/torchaudio_unittest/rnnt/autograd_cuda_test.py
  test/torchaudio_unittest/rnnt/autograd_impl.py
  test/torchaudio_unittest/rnnt/numpy_transducer.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cpu_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_cuda_test.py
  test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/rnnt/torchscript_consistency_impl.py
  test/torchaudio_unittest/transforms/autograd_cpu_test.py
  test/torchaudio_unittest/transforms/autograd_cuda_test.py
  test/torchaudio_unittest/transforms/autograd_test_impl.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cpu_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_cuda_test.py
  test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
  torchaudio/functional/__init__.py
  torchaudio/functional/functional.py
  torchaudio/prototype/rnnt_loss.py
  torchaudio/transforms.py
Labels: cla signed

#1718 Add additional guard to libsndfile
  torchaudio/_internal/module_utils.py
  torchaudio/backend/soundfile_backend.py
Labels: cla signed

#1681 Add basic filtfilt implementation
  docs/source/functional.rst
  test/torchaudio_unittest/functional/autograd_impl.py
  test/torchaudio_unittest/functional/batch_consistency_test.py
  test/torchaudio_unittest/functional/functional_impl.py
  test/torchaudio_unittest/functional/torchscript_consistency_impl.py
  torchaudio/functional/__init__.py
  torchaudio/functional/filtering.py
Labels: cla signed

#1720 Add sections to transforms docs
  docs/source/functional.rst
  docs/source/transforms.rst
Labels: cla signed

#1719 Added example for Fade transform
  torchaudio/transforms.py
Labels: cla signed

#1704 Refactor WaveRNN infer and move to codebase
  docs/source/models.rst
  examples/pipeline_wavernn/inference.py
  examples/pipeline_wavernn/wavernn_inference_wrapper.py
  test/torchaudio_unittest/models/models_test.py
  torchaudio/models/wavernn.py
Labels: cla signed

#1731 Add `.gitattributes`
  .gitattributes
Labels: cla signed

#1732 Add CUDA install step to Win Packaging jobs
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#1733 Pass CUDA architecture down to new-style CMAKE
  CMakeLists.txt
  build_tools/setup_helpers/extension.py
Labels: cla signed

#1557 feat: parallelized for-loop in lfilter
  torchaudio/csrc/lfilter.cpp
Labels: cla signed

#1734 Simplify the initialization process
  torchaudio/__init__.py
  torchaudio/extension/__init__.py
  torchaudio/extension/extension.py
Labels: fb-exported, cla signed

#1737 Fix CUDA build logic for _torchaudio.so
  third_party/kaldi/CMakeLists.txt
  torchaudio/csrc/CMakeLists.txt
Labels: cla signed

#1730 Enable Linux wheel/conda GPU package builds
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
  packaging/torchaudio/meta.yaml
Labels: cla signed

#1738 Increase no_output_timeout to 20m for WinConda
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1740 Fix WaveRNN training example
  examples/pipeline_wavernn/main.py
Labels: cla signed
