Repository pytorch/audio, pull requests merged in 2021-10, with the labels that each got.

#1811 Fix HuBERT xlarge configuration and test
  test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py
  torchaudio/models/wav2vec2/model.py
Labels: cla signed

#1816 Set release version and base PyTorch version
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed, ciflow/default

#1821 Add HUBERT_BASE and HUBERT_ASR_LARGE pretrained models
  build_tools/convert_fairseq_models.py
  docs/source/models.rst
  docs/source/refs.bib
  test/integration_tests/__init__.py
  test/integration_tests/conftest.py
  test/integration_tests/wav2vec2_model_test.py
  test/torchaudio_unittest/assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.flac
  torchaudio/models/__init__.py
  torchaudio/models/wav2vec2/pretrained.py
Labels: cla signed, ciflow/default

#1823 [fbsync] torchaudio: torch.quantization -> torch.ao.quantization
  examples/libtorchaudio/speech_recognition/build_pipeline_from_fairseq.py
  examples/libtorchaudio/speech_recognition/build_pipeline_from_huggingface_transformers.py
  test/torchaudio_unittest/models/wav2vec2/model_test.py
Labels: cla signed, ciflow/default

#1815 Replace dropout with Dropout
  torchaudio/models/wav2vec2/components.py
Labels: cla signed

#1826 [BC-Breaking] Remove deprecated dataset utils
  test/torchaudio_unittest/datasets/utils_test.py
  torchaudio/datasets/__init__.py
  torchaudio/datasets/utils.py
Labels: cla signed, BC-Breaking, ciflow/default

#1812 Rename build_tools to tools
  .circleci/unittest/linux/scripts/run_style_checks.sh
  setup.py
  tools/__init__.py
  tools/convert_fairseq_models.py
  tools/setup_helpers/__init__.py
  tools/setup_helpers/extension.py
  tools/travis/install.sh
  tools/travis/test_script.sh
Labels: cla signed, ciflow/default

#1824 Add the rest of HuBERT pretrained models
  docs/source/models.rst
  test/integration_tests/wav2vec2_model_test.py
  torchaudio/models/__init__.py
  torchaudio/models/wav2vec2/pretrained.py
Labels: cla signed, ciflow/default

#1801 Introduce Emformer
  docs/source/index.rst
  docs/source/prototype.rst
  docs/source/refs.bib
  test/torchaudio_unittest/prototype/__init__.py
  test/torchaudio_unittest/prototype/emformer_cpu_test.py
  test/torchaudio_unittest/prototype/emformer_gpu_test.py
  test/torchaudio_unittest/prototype/emformer_test_impl.py
  torchaudio/prototype/__init__.py
  torchaudio/prototype/emformer.py
Labels: cla signed

#1911 Add preprocessing scripts for HuBERT model training
  examples/hubert/preprocess.py
  examples/hubert/utils/__init__.py
  examples/hubert/utils/common_utils.py
  examples/hubert/utils/feature_utils.py
  examples/hubert/utils/kmeans.py
Labels: cla signed, ciflow/default
