Repository pytorch/audio, pull requests merged in 2025-08, with the labels that each got.

#4016 Revert "Disable asr cuda ctc tutorial (#4006)"
  docs/source/index.rst
  docs/source/models.decoder.rst
Labels: CLA Signed, ci-no-td

#4012 remove_prototype_integration_tests
  test/integration_tests/prototype/hifi_gan_pipeline_test.py
  test/integration_tests/prototype/vggish_pipeline_test.py
  test/integration_tests/rnnt_pipeline_test.py
Labels: CLA Signed

#4014 Use narrow instead of indexing by slices
  src/libtorchaudio/forced_align/cpu/compute.cpp
  src/libtorchaudio/forced_align/gpu/compute.cu
  src/libtorchaudio/lfilter.cpp
  src/torchaudio/functional/_alignment.py
Labels: CLA Signed

#4026 [TUTORIAL DEPENDENCY REMOVAL] Add cuda_ctc_decoder_tutorial to sphinx ignore regexp
  docs/source/conf.py
Labels: CLA Signed

#4028 [TUTORIAL DEPENDENCY REMOVAL] Use char-based pipeline instead of phoneme one for tacotron tutorial
  examples/tutorials/tacotron2_pipeline_tutorial.py
Labels: CLA Signed

#4031 Remove comparison dependencies and skipIfs
  .github/scripts/unittest-linux/install.sh
  .github/scripts/unittest-linux/run_test.sh
  .github/scripts/unittest-windows/environment.yml
  .github/scripts/unittest-windows/install.sh
  .github/workflows/unittest-linux-gpu.yml
  examples/hubert/utils/kmeans.py
  src/torchaudio/_internal/module_utils.py
  test/torchaudio_unittest/assets/kaldi_expected_results/test/torchaudio_unittest/functional/kaldi_compatibility_test.py__TestKaldiFloat32__test_sliding_window_cmn.pt
  test/torchaudio_unittest/assets/kaldi_expected_results/test/torchaudio_unittest/functional/kaldi_compatibility_test.py__TestKaldiFloat64__test_sliding_window_cmn.pt
  test/torchaudio_unittest/common_utils/__init__.py
  test/torchaudio_unittest/common_utils/case_utils.py
  test/torchaudio_unittest/compliance/kaldi/kaldi_compatibility_impl.py
  test/torchaudio_unittest/deprecation_test.py
  test/torchaudio_unittest/functional/functional_cpu_test.py
  test/torchaudio_unittest/functional/kaldi_compatibility_test_impl.py
  test/torchaudio_unittest/functional/sox_compatibility_test.py
  test/torchaudio_unittest/transforms/sox_compatibility_test.py
  test/torchaudio_unittest/utils/sox_utils_test.py
Labels: CLA Signed

#4030 Remove external dependencies for tutorials
  docs/requirements-tutorials.txt
  examples/tutorials/audio_feature_extractions_tutorial.py
Labels: CLA Signed

#4037 Remove unnecessary installations for linux CPU test
  .github/scripts/unittest-linux/install.sh
  .github/scripts/unittest-linux/run_test.sh
Labels: CLA Signed

#4040 Enable sox tests
  .github/scripts/unittest-linux/run_test.sh
  test/torchaudio_unittest/utils/sox_utils_test.py
Labels: CLA Signed

#4015 [Pyspeech] avoid .item call in feature_processing
  src/torchaudio/functional/functional.py
  src/torchaudio/transforms/_transforms.py
  test/torchaudio_unittest/functional/functional_impl.py
Labels: fb-exported, CLA Signed

#4036 Remove io directory
  docs/source/_templates/autosummary/io.rst
  docs/source/_templates/autosummary/io_class.rst
  docs/source/installation.rst
  docs/source/io.rst
  docs/source/torio.io.rst
  src/torchaudio/__init__.py
  src/torchaudio/io/__init__.py
  src/torchaudio/io/_effector.py
  src/torchaudio/io/_playback.py
Labels: CLA Signed

#4046 Remove sox
  CMakeLists.txt
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/sox_effects.rst
  docs/source/torchaudio.rst
  examples/libtorchaudio/augmentation/CMakeLists.txt
  examples/libtorchaudio/augmentation/README.md
  examples/libtorchaudio/augmentation/create_jittable_pipeline.py
  examples/libtorchaudio/augmentation/main.cpp
  examples/source_separation/conv_tasnet/train.py
  src/libtorchaudio/sox/CMakeLists.txt
  src/libtorchaudio/sox/effects.cpp
  src/libtorchaudio/sox/effects.h
  src/libtorchaudio/sox/effects_chain.cpp
  src/libtorchaudio/sox/effects_chain.h
  src/libtorchaudio/sox/io.cpp
  src/libtorchaudio/sox/io.h
  src/libtorchaudio/sox/pybind/pybind.cpp
  src/libtorchaudio/sox/types.cpp
  src/libtorchaudio/sox/types.h
  src/libtorchaudio/sox/utils.cpp
  src/libtorchaudio/sox/utils.h
  src/torchaudio/__init__.py
  src/torchaudio/_extension/__init__.py
  src/torchaudio/_extension/utils.py
  src/torchaudio/_internal/module_utils.py
  src/torchaudio/sox_effects/__init__.py
  src/torchaudio/sox_effects/sox_effects.py
  src/torchaudio/utils/__init__.py
  src/torchaudio/utils/sox_utils.py
  test/torchaudio_unittest/common_utils/case_utils.py
  third_party/sox/CMakeLists.txt
  third_party/sox/stub.c
  tools/setup_helpers/extension.py
Labels: CLA Signed

#4048 Remove prototype files
  docs/source/_templates/autosummary/model_class.rst
  docs/source/_templates/autosummary/prototype_model_class.rst
  docs/source/index.rst
  docs/source/prototype.datasets.rst
  docs/source/prototype.functional.rst
  docs/source/prototype.models.rst
  docs/source/prototype.pipelines.rst
  docs/source/prototype.rst
  docs/source/prototype.transforms.rst
  src/torchaudio/models/squim/objective.py
  src/torchaudio/prototype/__init__.py
  src/torchaudio/prototype/datasets/__init__.py
  src/torchaudio/prototype/datasets/musan.py
  src/torchaudio/prototype/functional/__init__.py
  src/torchaudio/prototype/functional/_dsp.py
  src/torchaudio/prototype/functional/_rir.py
  src/torchaudio/prototype/functional/functional.py
  src/torchaudio/prototype/models/__init__.py
  src/torchaudio/prototype/models/_conformer_wav2vec2.py
  src/torchaudio/prototype/models/_emformer_hubert.py
  src/torchaudio/prototype/models/conv_emformer.py
  src/torchaudio/prototype/models/hifi_gan.py
  src/torchaudio/prototype/models/rnnt.py
  src/torchaudio/prototype/models/rnnt_decoder.py
  src/torchaudio/prototype/pipelines/__init__.py
  src/torchaudio/prototype/pipelines/_vggish/__init__.py
  src/torchaudio/prototype/pipelines/_vggish/_vggish_impl.py
  src/torchaudio/prototype/pipelines/_vggish/_vggish_pipeline.py
  src/torchaudio/prototype/pipelines/hifigan_pipeline.py
  src/torchaudio/prototype/pipelines/rnnt_pipeline.py
  src/torchaudio/prototype/transforms/__init__.py
  src/torchaudio/prototype/transforms/_transforms.py
  test/torchaudio_unittest/deprecation_test.py
Labels: CLA Signed

#4070 Fix issues in documentation build.
  docs/source/index.rst
  docs/source/torchaudio.rst
  src/torchaudio/models/decoder/__init__.py
Labels: CLA Signed
